[theme]
theme = "nord-dark"

[icons]
icons = "material-nf"

[[block]]
block = "disk_space"
path = "/"
interval = 20
format = " $icon$available.eng(prefix:Gi)"
warning = 5.0
alert = 2.0
alert_unit = "GB"

[[block]]
block = "memory"
format = " $icon$mem_used.eng(prefix:Mi)/$mem_total.eng(prefix:Mi,pad_with:0)($mem_used_percents.eng(w:2,pad_with:0))"

[[block]]
block = "amd_gpu"
format = " $icon $vram_used.eng(prefix:Mi)/$vram_total.eng(prefix:Mi,pad_with:0)($vram_used_percents.eng(w:2,pad_with:0))"

[[block]]
block = "cpu"
interval = 2
format = " $icon $frequency.eng(prefix:M,force_prefix:true,w:4,pad_with:0)($utilization.eng(w:2,pad_with:0))"

[[block]]
block = "sound"
driver = "auto"
format = " $icon {$volume.eng(w:2)|}"
max_vol = 100
show_volume_when_muted = true
headphones_indicator = true

[[block]]
block = "time"
interval = 10
timezone = "Asia/Shanghai"
format = " $icon $timestamp.datetime(f:'%b %d %a, %I:%M %p')"

